from .user import UserViewSet
from .autor import AutorViewSet
from .genero import GeneroViewSet
from .idioma import IdiomaViewSet
from .status import StatusViewSet
from .editora import EditoraViewSet
from .frequencia import FrequenciaViewSet
from .classificacaoIdicativa import ClassificacaoIndicativaViewSet
from .hqs import HQViewSet
