# Generated by Django 5.1.7 on 2025-06-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classificacaoindicativa_editora_frequencia_idioma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificacaoIndicativa',
        ),
    ]
