# Generated by Django 5.1.7 on 2025-06-14 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_classificacaoindicativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_lancamento', models.DateField()),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(upload_to='capas/')),
                ('quantidade_capitulos', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.editora')),
                ('frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frequencia')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idioma')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
        ),
    ]
