# Generated by Django 5.1.7 on 2025-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hq_autor_alter_hq_editora_alter_hq_frequencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoIndicativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
