# Generated by Django 5.1.7 on 2025-08-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classificacaoindicativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hq',
            name='classificacao_indicativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.classificacaoindicativa'),
        ),
    ]
