# Generated by Django 5.1.7 on 2025-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hq',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
