# Generated by Django 5.1.7 on 2025-10-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_hq_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='hq',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
