# Generated by Django 5.1.7 on 2025-10-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hq_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hq',
            name='url',
        ),
    ]
