# Generated by Django 5.1.7 on 2025-10-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_hq_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('hq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='core.hq')),
            ],
        ),
    ]
