# Generated by Django 5.1.7 on 2025-11-21 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_bio_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='core.hq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hq')},
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to='core.hq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hq')},
            },
        ),
    ]
