from .user import User
from .autor import Autor
from .genero import Genero
from .idioma import Idioma
from .status import Status
from .editora import Editora
from .frequencia import Frequencia
from .classificacaoIdicativa import ClassificacaoIndicativa
from .hqs import HQ
from .hqUrl import HQUrl
